### ISSUE TITLE
Making msfpayload take into account added res files.

### ISSUE THREAD

**Issue by frenchbeard** [rapid7/metasploit-javapayload#24]
Hi,
I am working on a security threat awareness demo, focusing on BYOD and everything mobile.
I was wondering if there is an easy way to add a display to the Android Meterpreter (no actual app, but just change the Launch Activity to display simple things).
I tried modifying it just to display a background image, but even such a tiny modification, even thought compilation goes well, msf does not seem to include the picture in the final apk.

**Comment by frenchbeard** [comment]
Hi again, I come back to you after the last update.
If I understand the way the payload works now, it prevents any more display from the activity that launched (causes a WindowLeaked exception in my logcat).
```
E/WindowManager(27840): android.view.WindowLeaked: Activity com.metasploit.stage.CapitalePaysMondeActivity has leaked window com.android.internal.policy.impl.PhoneWindow$DecorView{3ace5450 V.E..... R.....ID 0,0-320,215} that was originally added here
```
Are there any way around it, or am I missing something ?

**Comment by timwr** [comment]
My guess is that the issue you're seeing is unrelated to the Payload, and without seeing the entire source it's difficult for me to debug. Make sure you're not calling finish() like the example does (that's only to hide the app launch).
You might be better off starting with a working project and just pasting in Payload.java?

**Comment by frenchbeard** [comment]
That's what I ended up doing. The Dialog trying to show up was indeed the problem in this case.

**Comment by Nicknam3** [comment]
Hi,

I try to bind android payload with a game (for a test). I noticed two version of the payload when i use apktool (smali code).

On kali (old metasploit version) i've this code on MainActivity.smali :

<code>
invoke-static {p0}, Lcom/metasploit/stage/Payload;->startWithContext(Landroid/content/Context;)V
</code>

but on a newer version:

<code>
invoke-static {v0}, Lcom/metasploit/stage/Payload;->startInPath(Ljava/lang/String;)V 
</code>

My game is not launching when i use the newer version (i copy this line on the MainActivity of my game).

Do you have an idea why my game does not start with the newer version of the payload ?
Maybe i need to add this line too on the MainActivity of my game:

<code>
invoke-virtual {v0}, Ljava/io/File;->toString()Ljava/lang/String;
</code>

Thx for your work timwr !

**Comment by timwr** [comment]
Sorry for the delay! Yes you'll need to copy the new (slightly more complicated) smali code, including the second line. You may need to pay attention to the registers. I'll put the old simpler code back so it's easier to invoke in the the next version.

**Comment by frenchbeard** [comment]
In my case, I simply built the application in android-studio, only using the Payload.java and the PayloadTrustManager.java. I had a slight issue though, when trying to modify / add / access anything in the Activity that launched the payload, the app simply crashed due to a NullPointerException when accessing the Activity itself (even only loading content from a layout file crashed).

The application consisted of a single activity that displayed a couple of static elements, and any access to its content after the call to startWithContext() caused said crash (I did not call finish() in the Activity, just launched the payload)

My question is : is it due to the Payload becoming the foreground process, therefore changing the context of the application, or is there a way to regain "control" over your app after launching the payload ?

**Comment by timwr** [comment]
Hi @Nicknam3, thanks for your feedback and sorry for the delay! We'll be adding that function call back with this change: https://github.com/rapid7/metasploit-javapayload/pull/34
I've put a simple script to backdoor any apk file here: https://github.com/timwr/metasploit-framework/blob/apk_backdoor/tools/apk_backdoor.rb and we'll be integrating it with the framework shortly (hopefully as part of msfvenom). Please note it relies on https://github.com/rapid7/metasploit-javapayload/pull/34

@frenchbeard I'm not sure what the problem you are experiencing could be. If you can provide the source and logs it might be easier to diagnose. Using the script mentioned above it seems possible to backdoor any apk and still retain the exact same app behaviour (assuming that using apktool and resigning the app does not modify the behaviour).

Feedback and testing is more than welcome :)

**Comment by frenchbeard** [comment]
I'm currently not working on the project anymore (will get baack on it in the beginning of June), but I'll try to be as verbose as possible.

**Comment by timwr** [comment]
No worries, we'll hopefully have fixed msfvenom to support --template by then.
If you have any issues feel free to re-open or preferably open a new issue.
Thanks again for the feedback.

**Comment by Nicknam3** [comment]
Thx timwr ! i'll try this new script soon.
You did a very good work :+1:
